# Generated by Django 3.2.12 on 2024-03-10 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='progetti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('data_caricamento', models.DateTimeField(auto_now_add=True)),
                ('stato_caricamento', models.IntegerField(choices=[(-10, 'N/D'), (-2, 'Errore Procedura'), (0, 'Ricevuto'), (1, 'Validazione in corso'), (4, 'Errori specifica'), (6, 'Importato')], default=-10)),
                ('nome_progetto', models.CharField(max_length=16)),
                ('comune', models.IntegerField()),
                ('approvazione', models.BooleanField(null=True)),
                ('riferimento_remoto', models.CharField(max_length=255, null=True)),
                ('risultato_validazione', models.CharField(max_length=16000, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progetti', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
