# Generated by Django 3.2.12 on 2024-03-10 18:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storagis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tratte_ln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtrattaln', models.BigIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratte_ln', to='storagis.progetti')),
            ],
        ),
        migrations.CreateModel(
            name='tratte_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idtrattainf', models.BigIntegerField(null=True)),
                ('idfeature', models.BigIntegerField(null=True)),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratte_inf', to='storagis.progetti')),
            ],
        ),
        migrations.CreateModel(
            name='nodi_rete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnodorete', models.BigIntegerField(null=True)),
                ('idfeature', models.BigIntegerField(null=True)),
                ('etichetta', models.CharField(max_length=255, null=True)),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodi_rete', to='storagis.progetti')),
            ],
        ),
        migrations.CreateModel(
            name='nodi_pt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnodopt', models.BigIntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodi_pt', to='storagis.progetti')),
            ],
        ),
        migrations.CreateModel(
            name='nodi_inf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnodoinf', models.BigIntegerField(null=True)),
                ('idfeature', models.BigIntegerField(null=True)),
                ('etichetta', models.CharField(max_length=255, null=True)),
                ('prj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodi_inf', to='storagis.progetti')),
            ],
        ),
    ]
